# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Rafał Chałupnik
title: Senior Backend Developer

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username: RafalChalupnik
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: rafal-chalupnik
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0003-4678-0842

# Additional icon links
# additional_links:
# - title: Google Scholar
#   icon: fa-brands fa-google-scholar
#   # icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: https://scholar.google.com/citations?hl=en&user=hfn1dPQAAAAJ

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Senior .NET Developer with 6+ years of experience designing and delivering high-quality backend systems and integrations. Strong technical ownership, proven expertise in system architecture, and experience facilitating agile teams. Passionate about building reliable, scalable software, mentoring colleagues, and growing into engineering leadership roles.

  <br/>

  Technical skills:

  <mark>C#/.NET</mark> <mark>Software Architecture</mark> <mark>Git/TFVC</mark> <mark>AWS/Azure</mark> <mark>Jira/Azure DevOps</mark> <mark>TeamCity/Azure Pipelines</mark> <mark>Oracle/SQL Server/PostgreSQL</mark> <mark>React/Vue.js</mark> <mark>Swift</mark>

  Soft skills:

  <mark>Willingness to learn</mark> <mark>Problem analysis & solving</mark> <mark>Teamwork</mark> <mark>Technical leadership</mark> <mark>Recruitment</mark>

  Languages:

  <mark>Polish (native)</mark> <mark>English (C1)</mark> <mark>Italian (A1)</mark> <mark>Spanish (A1)</mark>

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Shiji Group
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Backend Developer
        caption: June 2024 - Present
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            - Build and improve distributed Daylight PMS and REST APIs in .NET, enabling seamless integrations between PMS and external hotel partners
            - Design and deliver scalable microservices leveraging Kafka for event-driven communication and AWS for cloud deployment
            - Drive code quality and engineering standards through in-depth reviews, refactoring initiatives, and knowledge-sharing within the team
            - Take ownership of complex integrations and greenfield projects, translating ambiguous business requirements into production-ready solutions.
      - layout: left
        title: Titian Software
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Software Engineer
        caption: September 2021 - May 2024
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            - Acted as technical lead and Scrum Master for a cross-functional team enhancing Titian’s Mosaic sample management platform used by top Big Pharma companies
            - Designed and evolved architecture and REST APIs, improving reliability, scalability, and interoperability with third-party vendor systems
            - Led key modernization initiatives, including migration from **TFVC to Git** and **Bugzilla to Azure DevOps**, establishing new workflows, branching strategies, and automation pipelines
            - Championed code quality and engineering best practices, conducting in-depth reviews, mentoring developers, and introducing .NET features to improve maintainability
            - Drove process and delivery improvements in CI/CD and agile practices, working closely with QA, DevOps, and product management to increase deployment confidence and delivery cadence
            - Served as a technical reference point company-wide, advising teams on integration design, API development, and debugging complex production issues
      - layout: left
        title: Titian Software
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Software Engineer
        caption: August 2018 - August 2021
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            - Designed and implemented interfaces with external vendor systems, ensuring stable data exchange and system compatibility across distributed environments
            - Collaborated with QA and product teams to deliver reliable solutions within agile sprints
            - Participated in technical recruitment and internal IT support, contributing to infrastructure reliability and onboarding improvements
      - layout: left
        title: KRD BIG S.A.
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Junior .NET Developer
        caption: September 2017 - November 2017
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            - Contributed to the development and maintenance of service-oriented .NET applications supporting one of Poland’s largest debt and credit information databases
            - Assisted in implementing backend modules and optimizing existing components to improve performance and maintainability
            - Gained first hands-on experience with enterprise software delivery, version control, and agile collaboration practices while completing BSc studies

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: MSc Computer Systems Design
        # caption: October 2020 - Present
        # sub_title: PhD Information and Communication Technology
        # quote: >
        #   October 2020 - Present
        description: | # this will include new lines to allow paragraphs
          Wroclaw University of Science and Technology

          *March 2019 - July 2020*
      - layout: left
        title: BSc Computer Science
        # caption: October 2020 - Present
        # sub_title: PhD Information and Communication Technology
        # quote: >
        #   October 2020 - Present
        description: | # this will include new lines to allow paragraphs
          Wroclaw University of Science and Technology

          *October 2015 - January 2019*

  - title: Publications # Title for the section
    sub_title: Test subtitle
    layout: list # Type of content section (list/text)
    # Co-author of multiple articles and conference papers on Brain-Computer Interfaces and AI-based signal analysis
    content:
      # TODO: Newer pubs (ECAI?)
      - layout: left
        title: IEEE Transactions on Human-Machine Systems
        caption: 2022
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          [**Multifactor Authentication System Using Simplified EEG Brain–Computer Interface**](https://www.researchgate.net/publication/362819463_Multifactor_Authentication_System_Using_Simplified_EEG_Brain-Computer_Interface)

          *Katarzyna Bialas, Michal Kedziora, Rafal Chalupnik, Houbing Herbert Song*
      - layout: left
        title: The 36th International Conference on Advanced Information Networking and Applications
        caption: 2022
        sub_title: Sydney, Australia
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          [**Using Simplified EEG-Based Brain Computer Interface and Decision Tree Classifier for Emotions Detection**](https://www.researchgate.net/publication/359598359_Using_Simplified_EEG-Based_Brain_Computer_Interface_and_Decision_Tree_Classifier_for_Emotions_Detection)

          *Rafal Chalupnik, Katarzyna Bialas, Zofia Majewska, Michal Kedziora*

# Footer
# footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
